### ISSUE TITLE
NullPointerException when add a redstone torch 

### ISSUE THREAD

**Issue by SKlayer** [TheCBProject/CBMultipart#100]
when you put TNT and redstonetorch like this:
![TNTBOOM](https://user-images.githubusercontent.com/20183734/130054591-e5509db9-1386-4a6f-a0b1-614c5488781f.png)

Will got this, and internal server crash.
`
Caused by: java.lang.NullPointerException
	at codechicken.multipart.minecraft.RedstoneTorchPart.onNeighborChanged(RedstoneTorchPart.java:87) ~[RedstoneTorchPart.class:?]
	at codechicken.multipart.minecraft.RedstoneTorchPart.onAdded(RedstoneTorchPart.java:183) ~[RedstoneTorchPart.class:?]
	at codechicken.multipart.TMultiPart.onConverted(TMultiPart.scala:231) ~[TMultiPart.class:?]
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:81) ~[MultipartGenerator$.class:?]
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:723) ~[TileMultipart$.class:?]
	at codechicken.multipart.ItemPlacementHelper$.place(ItemPlacementHelper.scala:57) ~[ItemPlacementHelper$.class:?]
	at codechicken.multipart.handler.MultipartSPH$.handlePacket(packethandlers.scala:92) ~[MultipartSPH$.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133) ~[PacketCustom$ServerInboundHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_291]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 5 more
`

**Comment by covers1624** [comment]
This appears to have been resolved in the 1.16 port.

Unfortunately, 1.12 is not supported anymore.
