### ISSUE TITLE
Issue with CB_Multipart and CHickenLib.

### ISSUE THREAD

**Issue by Sodisna** [TheCBProject/CBMultipart#114]
Seems to crash upon loading. The game
I'm not running any mods and just 
CBMultipart-1.16.5-3.0.2.120-universal
CodeChickenLib-1.16.5-4.0.3.434-universal
Scorge-3.1.3
Forge 36.2.8

``---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/2/21, 7:39 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?] {}
-- MOD cb_microblock --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {re:classloading,re:classloading}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.scorge.lang.ScorgeModContainer.constructMod(ScorgeModContainer.scala:48) ~[?:3.1.3] {re:classloading}
		at net.minecraftforge.scorge.lang.ScorgeModContainer.$anonfun$new$1(ScorgeModContainer.scala:23) ~[?:3.1.3] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Caused by 1: java.lang.ExceptionInInitializerError
		at codechicken.multipart.util.MultiPartGenerator.<init>(MultiPartGenerator.java:60) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.multipart.util.MultiPartGenerator.<clinit>(MultiPartGenerator.java:52) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.MicroBlockGenerator$.<init>(MicroBlockGenerator.scala:13) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.MicroBlockGenerator$.<clinit>(MicroBlockGenerator.scala:13) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.MicroblockFactory.<init>(MicroblockFactory.scala:20) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.CommonMicroFactory.<init>(MicroblockFactory.scala:38) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.FaceMicroFactory$.<init>(FaceMicroblock.scala:27) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.FaceMicroFactory$.<clinit>(FaceMicroblock.scala:27) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.handler.MicroblockProxyServer.<init>(proxies.scala:38) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.handler.MicroblockProxyClient.<init>(proxies.scala:97) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.handler.MicroblockMod.$anonfun$proxy$2(MicroblockMod.scala:31) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[forge:?] {re:classloading}
		at codechicken.microblock.handler.MicroblockMod.<init>(MicroblockMod.scala:32) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {re:classloading,re:classloading,re:classloading}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.scorge.lang.ScorgeModContainer.constructMod(ScorgeModContainer.scala:48) ~[?:3.1.3] {re:classloading}
		at net.minecraftforge.scorge.lang.ScorgeModContainer.$anonfun$new$1(ScorgeModContainer.scala:23) ~[?:3.1.3] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Caused by 2: java.lang.RuntimeException: Unable to retrieve methods via reflection.
		at codechicken.mixin.api.MixinBackend$SimpleMixinBackend.<clinit>(MixinBackend.java:80) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.multipart.util.MultiPartGenerator.<init>(MultiPartGenerator.java:60) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.multipart.util.MultiPartGenerator.<clinit>(MultiPartGenerator.java:52) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.MicroBlockGenerator$.<init>(MicroBlockGenerator.scala:13) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.MicroBlockGenerator$.<clinit>(MicroBlockGenerator.scala:13) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.MicroblockFactory.<init>(MicroblockFactory.scala:20) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.CommonMicroFactory.<init>(MicroblockFactory.scala:38) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.FaceMicroFactory$.<init>(FaceMicroblock.scala:27) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.FaceMicroFactory$.<clinit>(FaceMicroblock.scala:27) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.handler.MicroblockProxyServer.<init>(proxies.scala:38) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.handler.MicroblockProxyClient.<init>(proxies.scala:97) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at codechicken.microblock.handler.MicroblockMod.$anonfun$proxy$2(MicroblockMod.scala:31) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[forge:?] {re:classloading}
		at codechicken.microblock.handler.MicroblockMod.<init>(MicroblockMod.scala:32) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.scorge.lang.ScorgeModContainer.constructMod(ScorgeModContainer.scala:48) ~[?:3.1.3] {re:classloading}
		at net.minecraftforge.scorge.lang.ScorgeModContainer.$anonfun$new$1(ScorgeModContainer.scala:23) ~[?:3.1.3] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: CBMultipart-1.16.5-3.0.2.120-universal.jar
	Failure message: Failed to load mod
	Mod Version: 3.0.2.120
	Mod Issue URL: https://github.com/TheCBProject/ForgeMultipart
	Exception message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @110ce793
Stacktrace:
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?] {}
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?] {}
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?] {}
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?] {}
	at codechicken.mixin.api.MixinBackend$SimpleMixinBackend.<clinit>(MixinBackend.java:77) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.multipart.util.MultiPartGenerator.<init>(MultiPartGenerator.java:60) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.multipart.util.MultiPartGenerator.<clinit>(MultiPartGenerator.java:52) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.MicroBlockGenerator$.<init>(MicroBlockGenerator.scala:13) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.MicroBlockGenerator$.<clinit>(MicroBlockGenerator.scala:13) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.MicroblockFactory.<init>(MicroblockFactory.scala:20) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.CommonMicroFactory.<init>(MicroblockFactory.scala:38) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.FaceMicroFactory$.<init>(FaceMicroblock.scala:27) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.FaceMicroFactory$.<clinit>(FaceMicroblock.scala:27) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.handler.MicroblockProxyServer.<init>(proxies.scala:38) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.handler.MicroblockProxyClient.<init>(proxies.scala:97) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at codechicken.microblock.handler.MicroblockMod.$anonfun$proxy$2(MicroblockMod.scala:31) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[forge:?] {re:classloading}
	at codechicken.microblock.handler.MicroblockMod.<init>(MicroblockMod.scala:32) ~[cb_multipart:1.16.5-3.0.2.120] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.scorge.lang.ScorgeModContainer.constructMod(ScorgeModContainer.scala:48) ~[?:3.1.3] {re:classloading}
	at net.minecraftforge.scorge.lang.ScorgeModContainer.$anonfun$new$1(ScorgeModContainer.scala:23) ~[?:3.1.3] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1847068184 bytes (1761 MB) / 2936012800 bytes (2800 MB) up to 12750684160 bytes (12160 MB)
	CPUs: 16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx12160m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.8-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.8-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.8-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.8-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.8
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		scorge@3.1.3
	Mod List: 
		forge-1.16.5-36.2.8-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.8-universal.jar                 |Forge                         |forge                         |36.2.8              |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		CodeChickenLib-1.16.5-4.0.3.434-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.3.434           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CBMultipart-1.16.5-3.0.2.120-universal.jar        |CBMultipart                   |cb_multipart                  |3.0.2.120           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
	Crash Report UUID: 6ff778b4-b39c-4844-a991-e18280b39037``

**Comment by squarism** [comment]
Try Java 8 or Java 11.

**Comment by Sproinks** [comment]
Had the same problem.  I was using Java 16.  I switched to 8 and it worked.  Someone else was using 11.  Try an older Java version.  If you are on 16 for 1.17/18, have two installed and switch with MultiMC (as you are using).

**Comment by covers1624** [comment]
Java 16 is not supported. Use Java 8-15.
