### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by Nessiesson** [TheCBProject/CBMultipart#70]
Ran into strange crash when logging into modded server next to a nonmoving projectred frame machine (modlist in attached crashlog file). This seems to have broken some projectred wires, specifically: https://i.imgur.com/nOuvmPc.png
Furthermore, attempting to move the frame machine again has made some weird null block and has caused some strange issues with wires not connecting as they should: https://i.imgur.com/KuhUIwR.png (**edit: the tile.null.name is caused by oneprobe or so it seems whenever you're looking at FMP that are "too far away".)

```---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2019-10-31 21:04:46 CET
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: 0
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3442)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: 0
    at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:51)
    at scala.collection.immutable.List.apply(List.scala:83)
    at codechicken.multipart.TileMultipart$.handlePacket(TileMultipart.scala:764)
    at codechicken.multipart.handler.MultipartCPH$.handleCompressedTileData(packethandlers.scala:66)
    at codechicken.multipart.handler.MultipartCPH$.handlePacket(packethandlers.scala:37)
    at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:110)
    at codechicken.lib.packet.PacketCustom$ClientInboundHandler.lambda$handle$0(PacketCustom.java:108)
    at codechicken.lib.packet.PacketCustom$ClientInboundHandler$$Lambda$1964/643554258.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more
```
[crash-2019-10-31_21.04.42-client.txt](https://github.com/TheCBProject/ForgeMultipart/files/3795653/crash-2019-10-31_21.04.42-client.txt)
[crash-2019-10-31_21.04.43-client.txt](https://github.com/TheCBProject/ForgeMultipart/files/3795654/crash-2019-10-31_21.04.43-client.txt)

**Comment by covers1624** [comment]
Unfortunately, 1.12 is no longer supported.
