### ISSUE TITLE
[1.16.5] ClassCastException crash: ClientWorld cannot be cast to ServerWorld

### ISSUE THREAD

**Issue by ArcanoxDragon** [TheCBProject/CBMultipart#87]
I'm doing a bit of canary testing of the latest 1.16.5 build on the Maven server for CBMultipart, and I discovered a crash that I triggered by shift-right-clicking a cover in creative mode on a single-player world. The first cover just disappeared like I had broken it, but the second one crashed with the following stack trace:

```
Description: Ticking block entity
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at codechicken.multipart.network.MultiPartSPH.sendDescUpdate(MultiPartSPH.java:64) ~[?:1.16.5-3.0.1.110] {re:classloading}
	at codechicken.multipart.util.MultiPartLoadHandler$TileNBTContainer.func_73660_a(MultiPartLoadHandler.java:81) ~[?:1.16.5-3.0.1.110] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:1252) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:APP:create.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:175) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.18.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$498/1001702066.call(Unknown Source) [forge-1.16.5-36.1.18.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
```

Makes sense, because `ServerWorld` is only for _dedicated_ servers.

**Comment by ArcanoxDragon** [comment]
Full crash report with loaded mods list:

https://hastebin.com/udufihuqos.yaml

**Comment by ArcanoxDragon** [comment]
This crash actually put my world into a corrupted state where the player cannot open their inventory, switch hotbar slots, or really do anything except attempt to right-click with what appears to be an empty hand, which re-triggers the crash. I'll make a zip of the world which I'd be happy to share privately with a dev.

**Comment by ArcanoxDragon** [comment]
Alright, did some more research. This seems to be Carry On being naughty with tile entities. I'm going to write a PR to blacklist the multipart Tile Entity from Carry On, which should prevent this from happening.

**Comment by covers1624** [comment]
Hmm, interesting, that would make sense. How does this bug occur with Carry On? Is it after placing the part back down?

**Comment by ArcanoxDragon** [comment]
> Hmm, interesting, that would make sense. How does this bug occur with Carry On? Is it after placing the part back down?
> 
> What I suspect they are doing is placing the part back down on both the server and client-side. However, that's not how TileNBTContainer works, it should never attempt to do things on the client. We can likely resolve this issue in Multipart and leave Carry On as-is by adding some checks to `tick`, to ensure we are on the server-side before doing anything.

Yeah, that appears to be exactly what's happening. If I add a `if (!level.isClientSide)` check before the call to `MultiPartSPH.sendDescUpdate` in `tick`, I can actually place down the carried multipart successfully without crashing. The main issue at that point is that the item renders as "Air" and does not render in the hotbar; this made it **_really_** difficult to figure out what was triggering this. I spent a good 2 hours trying to trigger different situations in a single player dev environment but was unable to. Then I remembered that the pack I was triggering this crash on contains Carry On, and as soon as I installed that into the dev environment, I was immediately able to reproduce it 😄

I'm not sure what it'd take to get the multipart block to render right as a "Carry On tile"; if that's easy, then it would be kind of neat to be able to pick up/set down multiparts.

**Comment by covers1624** [comment]
Fantastic. As a first pass at a fix, I would accept a pr adding `if (level.isClientSide) return;` to the Top of the Tick method. Nothing in there should be running on the client-side anyway.

As for the rendering issue. I am unsure, it would depend on how Carry On is rendering the Item model for Multipart. Since it doesn't actually have an ItemBlock, and we use a hook to render parts in the world, they would likely need to call some different methods. As they are probably just grabbing the block quads.

**Comment by ArcanoxDragon** [comment]
Great; I'll submit a PR with that fix shortly 😃
